version: 1.0

snow:
  - id: 545804 # Milo Express

notifications:
  jira:
    default:
      project: MWPW # Mandatory
      filters:
        include:
          risk_rating: R5
      fields:
        customfield_11800: MWPW-145743 #epic link
        customfield_12900: 
          value: Express dev
        watchers:
          - dstrong
          - vhargrave
          - jinglhua
          - rea01581
          - all42238
          - all66020
          - cod87753
          - apganapa
        labels:
          - "OriginatingProcess=Kodiak"
          - "security"
          - "kodiak-ticket"
        components:
          - name: "DevOps Security"
